import { db } from '@database/db.connection';
import { Contact, contacts, senders } from '@database/schema';
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { and, count, desc, eq, ilike, inArray, or } from 'drizzle-orm';
import { AuditWriteService } from '../audit/audit-write.service';
import { CreateContactDto } from './dto/create-contact.dto';
import { UpdateContactDto } from './dto/update-contact.dto';

/**
 * Paginated response interface for contacts list
 */
export interface PaginatedContactsResponse {
  data: Contact[];
  pagination: {
    page: number;
    limit: number;
    totalItems: number;
    totalPages: number;
  };
}

/**
 * Contacts Service
 * Manages WhatsApp contacts
 *
 * Note: Contacts are global and can be messaged by any sender.
 * There is no sender-contact relationship - any registered WhatsApp number can message any contact.
 */
@Injectable()
export class ContactsService {
  private readonly logger = new Logger(ContactsService.name);

  constructor(private readonly auditWriteService: AuditWriteService) {}

  /**
   * Create a new contact
   */
  async create(
    userId: number,
    createContactDto: CreateContactDto,
  ): Promise<Contact> {
    try {
      // Verify user has at least one active sender (they need a WhatsApp number to send messages)
      const userSenders = await db.query.senders.findFirst({
        where: and(eq(senders.userId, userId), eq(senders.isActive, true)),
      });

      if (!userSenders) {
        throw new Error(
          'You need at least one registered WhatsApp number to create contacts',
        );
      }

      // Check if contact already exists (active or inactive) by phone number
      // phoneNumber now includes the country code, so it's a unique identifier
      const existingContact = await db.query.contacts.findFirst({
        where: eq(contacts.phoneNumber, createContactDto.phoneNumber),
      });

      if (existingContact) {
        this.logger.log(
          `Found existing contact (id: ${existingContact.id}, isActive: ${existingContact.isActive})`,
        );

        if (existingContact.isActive) {
          throw new Error('Contact with this phone number already exists');
        }

        // If soft-deleted contact exists with same phone and country code, reactivate it
        const [reactivated] = await db
          .update(contacts)
          .set({
            firstName: createContactDto.firstName,
            lastName: createContactDto.lastName || null,
            countryCode: createContactDto.countryCode,
            phoneNumber: createContactDto.phoneNumber,
            avatar: createContactDto.avatar || null,
            isActive: true,
            updatedAt: new Date(),
          })
          .where(eq(contacts.id, existingContact.id))
          .returning();

        this.logger.log(`Contact reactivated: ${existingContact.contactId}`);

        await this.auditWriteService.logContactCreated({
          userId,
          entityId: reactivated.contactId,
          entityName:
            `${reactivated.firstName || ''} ${reactivated.lastName || ''}`.trim(),
          metadata: { phoneNumber: reactivated.phoneNumber },
        });

        return reactivated;
      }

      // No existing contact found, create a new one
      // contactId is auto-generated by database as UUID
      const [contact] = await db
        .insert(contacts)
        .values({
          firstName: createContactDto.firstName,
          lastName: createContactDto.lastName || null,
          countryCode: createContactDto.countryCode,
          phoneNumber: createContactDto.phoneNumber,
          avatar: createContactDto.avatar || null,
          isActive: true,
        })
        .returning();

      this.logger.log(`Contact created: ${contact.contactId}`);

      await this.auditWriteService.logContactCreated({
        userId,
        entityId: contact.contactId,
        entityName:
          `${contact.firstName || ''} ${contact.lastName || ''}`.trim(),
        metadata: { phoneNumber: contact.phoneNumber },
      });

      return contact;
    } catch (error) {
      this.logger.error(`Error creating contact: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get all contacts with pagination and optional search
   * Contacts are global - any sender can message any contact
   *
   * @param userId - User ID to verify sender access
   * @param page - Page number (1-indexed)
   * @param limit - Items per page
   * @param search - Optional search query for first name, last name, or phone number
   */
  async findAll(
    userId: number,
    page: number = 1,
    limit: number = 20,
    search?: string,
  ): Promise<PaginatedContactsResponse> {
    try {
      // Verify user has at least one active sender
      const userSender = await db.query.senders.findFirst({
        where: and(eq(senders.userId, userId), eq(senders.isActive, true)),
      });

      // If user has no senders, return empty result
      if (!userSender) {
        this.logger.log(`User ${userId} has no active senders`);
        return {
          data: [],
          pagination: {
            page,
            limit,
            totalItems: 0,
            totalPages: 0,
          },
        };
      }

      // Build where conditions
      const conditions = [eq(contacts.isActive, true)];

      // Add search filter if provided
      if (search && search.trim()) {
        const searchTerm = `%${search.trim()}%`;
        conditions.push(
          or(
            ilike(contacts.firstName, searchTerm),
            ilike(contacts.lastName, searchTerm),
            ilike(contacts.phoneNumber, searchTerm),
          )!,
        );
      }

      // Get total count for pagination
      const [countResult] = await db
        .select({ count: count() })
        .from(contacts)
        .where(and(...conditions));

      const totalItems = countResult?.count || 0;
      const totalPages = Math.ceil(totalItems / limit);
      const offset = (page - 1) * limit;

      // Fetch paginated results
      const result = await db.query.contacts.findMany({
        where: and(...conditions),
        orderBy: [desc(contacts.lastMessageTime), desc(contacts.contactId)],
        limit,
        offset,
      });

      return {
        data: result,
        pagination: {
          page,
          limit,
          totalItems,
          totalPages,
        },
      };
    } catch (error) {
      this.logger.error(`Error fetching contacts: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get a single contact
   */
  async findOne(contactId: string): Promise<Contact> {
    try {
      const contact = await db.query.contacts.findFirst({
        where: eq(contacts.contactId, contactId),
      });

      if (!contact) {
        throw new NotFoundException(`Contact ${contactId} not found`);
      }

      return contact;
    } catch (error) {
      this.logger.error(`Error fetching contact: ${error.message}`);
      throw error;
    }
  }

  /**
   * Update a contact
   */
  async update(
    userId: number,
    contactId: string,
    updateContactDto: UpdateContactDto,
  ): Promise<Contact> {
    try {
      // Verify contact exists
      const existing = await this.findOne(contactId);

      const updateData: Record<string, unknown> = {
        updatedAt: new Date(),
      };

      if (updateContactDto.firstName) {
        updateData.firstName = updateContactDto.firstName;
      }
      if (updateContactDto.lastName !== undefined) {
        updateData.lastName = updateContactDto.lastName || null;
      }
      if (updateContactDto.email !== undefined) {
        updateData.email = updateContactDto.email || null;
      }
      if (updateContactDto.avatar !== undefined) {
        updateData.avatar = updateContactDto.avatar || null;
      }
      if (updateContactDto.language !== undefined) {
        updateData.language = updateContactDto.language || null;
      }

      // If phone details changed, update separately
      if (updateContactDto.countryCode) {
        updateData.countryCode = updateContactDto.countryCode;
      }
      if (updateContactDto.phoneNumber) {
        updateData.phoneNumber = updateContactDto.phoneNumber;
      }

      const [updated] = await db
        .update(contacts)
        .set(updateData)
        .where(eq(contacts.contactId, contactId))
        .returning();

      this.logger.log(`Contact updated: ${contactId}`);

      await this.auditWriteService.logContactUpdated({
        userId,
        entityId: contactId,
        entityName:
          `${updated.firstName || ''} ${updated.lastName || ''}`.trim(),
        changes: this.auditWriteService.buildChanges(existing, updated, [
          'firstName',
          'lastName',
          'email',
          'phoneNumber',
          'countryCode',
          'avatar',
          'language',
        ]),
      });

      return updated;
    } catch (error) {
      this.logger.error(`Error updating contact: ${error.message}`);
      throw error;
    }
  }

  /**
   * Soft delete a contact (mark as inactive)
   */
  async delete(userId: number, contactId: string): Promise<void> {
    try {
      // Verify contact exists
      const existing = await this.findOne(contactId);

      const result = await db
        .update(contacts)
        .set({
          isActive: false,
          updatedAt: new Date(),
        })
        .where(eq(contacts.contactId, contactId))
        .returning();

      if (!result || result.length === 0) {
        throw new Error(`Failed to delete contact: ${contactId}`);
      }

      this.logger.log(`Contact deleted: ${contactId}`);

      await this.auditWriteService.logContactDeleted({
        userId,
        entityId: contactId,
        entityName:
          `${existing.firstName || ''} ${existing.lastName || ''}`.trim(),
        metadata: { phoneNumber: existing.phoneNumber },
      });
    } catch (error) {
      this.logger.error(`Error deleting contact: ${error.message}`);
      throw error;
    }
  }

  /**
   * Bulk delete multiple contacts (soft delete)
   * @param contactIds - Array of contact IDs to delete
   * @returns Number of contacts deleted
   */
  async bulkDelete(userId: number, contactIds: string[]): Promise<number> {
    if (!contactIds || contactIds.length === 0) {
      return 0;
    }

    try {
      const result = await db
        .update(contacts)
        .set({
          isActive: false,
          updatedAt: new Date(),
        })
        .where(
          and(
            inArray(contacts.contactId, contactIds),
            eq(contacts.isActive, true),
          ),
        )
        .returning();

      const deletedCount = result.length;
      this.logger.log(`Bulk deleted ${deletedCount} contacts`);

      if (deletedCount === 1) {
        // Single contact — log as individual deletion with name
        const c = result[0];
        const contactName =
          `${c.firstName || ''} ${c.lastName || ''}`.trim() ||
          c.phoneNumber ||
          c.contactId;
        await this.auditWriteService.logContactDeleted({
          userId,
          entityId: c.contactId,
          entityName: contactName,
          metadata: { phoneNumber: c.phoneNumber },
        });
      } else if (deletedCount > 1) {
        // True bulk — include names so the audit entry is useful
        const contactNames = result.map((c) => {
          const name =
            `${c.firstName || ''} ${c.lastName || ''}`.trim() ||
            c.phoneNumber ||
            c.contactId;
          return name;
        });
        await this.auditWriteService.logContactsBulkDeleted({
          userId,
          count: deletedCount,
          metadata: { contactIds, contactNames },
        });
      }

      return deletedCount;
    } catch (error) {
      this.logger.error(`Error bulk deleting contacts: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get contact by phone number
   * Handles both formats: with '+' prefix (e.g., +59167131914) and without (e.g., 59167131914)
   */
  async findByPhoneNumber(phoneNumber: string): Promise<Contact | null> {
    try {
      // Normalize the phone number - ensure it has the + prefix
      const normalizedPhone = phoneNumber.startsWith('+')
        ? phoneNumber
        : `+${phoneNumber}`;

      // Also try without the + in case the DB has it stored differently
      const phoneWithoutPlus = phoneNumber.replace(/^\+/, '');

      // First try with the + prefix (standard E.164 format)
      let contact = await db.query.contacts.findFirst({
        where: eq(contacts.phoneNumber, normalizedPhone),
      });

      // If not found, try without the + prefix
      if (!contact) {
        contact = await db.query.contacts.findFirst({
          where: eq(contacts.phoneNumber, phoneWithoutPlus),
        });
      }

      return contact ?? null;
    } catch (error) {
      this.logger.error(`Error finding contact by phone: ${error.message}`);
      return null;
    }
  }

  /**
   * Update contact with last message info
   */
  async updateLastMessage(
    contactId: string,
    messagePreview: string,
    messageType: string = 'text',
  ): Promise<void> {
    try {
      await db
        .update(contacts)
        .set({
          lastMessageTime: new Date(),
          lastMessagePreview: messagePreview,
          lastMessageType: messageType,
          updatedAt: new Date(),
        })
        .where(eq(contacts.contactId, contactId));
    } catch (error) {
      this.logger.error(
        `Error updating contact last message: ${error.message}`,
      );
    }
  }
}
