import { db } from '@database/db.connection';
import { Contact, contacts, senders } from '@database/schema';
import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { and, desc, eq } from 'drizzle-orm';
import { CreateContactDto } from './dto/create-contact.dto';
import { UpdateContactDto } from './dto/update-contact.dto';

/**
 * Contacts Service
 * Manages WhatsApp contacts
 *
 * Note: Contacts are global and can be messaged by any sender.
 * There is no sender-contact relationship - any registered WhatsApp number can message any contact.
 */
@Injectable()
export class ContactsService {
  private readonly logger = new Logger(ContactsService.name);

  /**
   * Create a new contact
   */
  async create(
    userId: number,
    createContactDto: CreateContactDto,
  ): Promise<Contact> {
    try {
      // Verify user has at least one active sender (they need a WhatsApp number to send messages)
      const userSenders = await db.query.senders.findFirst({
        where: and(eq(senders.userId, userId), eq(senders.isActive, true)),
      });

      if (!userSenders) {
        throw new Error(
          'You need at least one registered WhatsApp number to create contacts',
        );
      }

      // Check if contact already exists (active or inactive) by phone number
      // phoneNumber now includes the country code, so it's a unique identifier
      const existingContact = await db.query.contacts.findFirst({
        where: eq(contacts.phoneNumber, createContactDto.phoneNumber),
      });

      if (existingContact) {
        this.logger.log(
          `Found existing contact (id: ${existingContact.id}, isActive: ${existingContact.isActive})`,
        );

        if (existingContact.isActive) {
          throw new Error('Contact with this phone number already exists');
        }

        // If soft-deleted contact exists with same phone and country code, reactivate it
        const [reactivated] = await db
          .update(contacts)
          .set({
            firstName: createContactDto.firstName,
            lastName: createContactDto.lastName || null,
            countryCode: createContactDto.countryCode,
            phoneNumber: createContactDto.phoneNumber,
            avatar: createContactDto.avatar || null,
            isActive: true,
            updatedAt: new Date(),
          })
          .where(eq(contacts.id, existingContact.id))
          .returning();

        this.logger.log(`Contact reactivated: ${existingContact.contactId}`);

        return reactivated;
      }

      // No existing contact found, create a new one
      // contactId is auto-generated by database as UUID
      const [contact] = await db
        .insert(contacts)
        .values({
          firstName: createContactDto.firstName,
          lastName: createContactDto.lastName || null,
          countryCode: createContactDto.countryCode,
          phoneNumber: createContactDto.phoneNumber,
          avatar: createContactDto.avatar || null,
          isActive: true,
        })
        .returning();

      this.logger.log(`Contact created: ${contact.contactId}`);

      return contact;
    } catch (error) {
      this.logger.error(`Error creating contact: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get all contacts
   * Contacts are global - any sender can message any contact
   */
  async findAll(
    userId: number,
    skip: number = 0,
    take: number = 50,
  ): Promise<Contact[]> {
    try {
      // Verify user has at least one active sender
      const userSender = await db.query.senders.findFirst({
        where: and(eq(senders.userId, userId), eq(senders.isActive, true)),
      });

      // If user has no senders, return empty array (they need a WhatsApp number first)
      if (!userSender) {
        this.logger.log(`User ${userId} has no active senders`);
        return [];
      }

      // Return all active contacts, ordered by last message time
      const result = await db.query.contacts.findMany({
        where: eq(contacts.isActive, true),
        orderBy: desc(contacts.lastMessageTime),
        limit: take,
        offset: skip,
      });

      return result;
    } catch (error) {
      this.logger.error(`Error fetching contacts: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get a single contact
   */
  async findOne(contactId: string): Promise<Contact> {
    try {
      const contact = await db.query.contacts.findFirst({
        where: eq(contacts.contactId, contactId),
      });

      if (!contact) {
        throw new NotFoundException(`Contact ${contactId} not found`);
      }

      return contact;
    } catch (error) {
      this.logger.error(`Error fetching contact: ${error.message}`);
      throw error;
    }
  }

  /**
   * Update a contact
   */
  async update(
    contactId: string,
    updateContactDto: UpdateContactDto,
  ): Promise<Contact> {
    try {
      // Verify contact exists
      await this.findOne(contactId);

      const updateData: Record<string, unknown> = {
        updatedAt: new Date(),
      };

      if (updateContactDto.firstName) {
        updateData.firstName = updateContactDto.firstName;
      }
      if (updateContactDto.lastName !== undefined) {
        updateData.lastName = updateContactDto.lastName || null;
      }
      if (updateContactDto.email !== undefined) {
        updateData.email = updateContactDto.email || null;
      }
      if (updateContactDto.avatar !== undefined) {
        updateData.avatar = updateContactDto.avatar || null;
      }
      if (updateContactDto.language !== undefined) {
        updateData.language = updateContactDto.language || null;
      }

      // If phone details changed, update separately
      if (updateContactDto.countryCode) {
        updateData.countryCode = updateContactDto.countryCode;
      }
      if (updateContactDto.phoneNumber) {
        updateData.phoneNumber = updateContactDto.phoneNumber;
      }

      const [updated] = await db
        .update(contacts)
        .set(updateData)
        .where(eq(contacts.contactId, contactId))
        .returning();

      this.logger.log(`Contact updated: ${contactId}`);

      return updated;
    } catch (error) {
      this.logger.error(`Error updating contact: ${error.message}`);
      throw error;
    }
  }

  /**
   * Soft delete a contact (mark as inactive)
   */
  async delete(contactId: string): Promise<void> {
    try {
      // Verify contact exists
      await this.findOne(contactId);

      const result = await db
        .update(contacts)
        .set({
          isActive: false,
          updatedAt: new Date(),
        })
        .where(eq(contacts.contactId, contactId))
        .returning();

      if (!result || result.length === 0) {
        throw new Error(`Failed to delete contact: ${contactId}`);
      }

      this.logger.log(`Contact deleted: ${contactId}`);
    } catch (error) {
      this.logger.error(`Error deleting contact: ${error.message}`);
      throw error;
    }
  }

  /**
   * Get contact by phone number
   * Handles both formats: with '+' prefix (e.g., +59167131914) and without (e.g., 59167131914)
   */
  async findByPhoneNumber(phoneNumber: string): Promise<Contact | null> {
    try {
      // Normalize the phone number - ensure it has the + prefix
      const normalizedPhone = phoneNumber.startsWith('+')
        ? phoneNumber
        : `+${phoneNumber}`;

      // Also try without the + in case the DB has it stored differently
      const phoneWithoutPlus = phoneNumber.replace(/^\+/, '');

      // First try with the + prefix (standard E.164 format)
      let contact = await db.query.contacts.findFirst({
        where: eq(contacts.phoneNumber, normalizedPhone),
      });

      // If not found, try without the + prefix
      if (!contact) {
        contact = await db.query.contacts.findFirst({
          where: eq(contacts.phoneNumber, phoneWithoutPlus),
        });
      }

      return contact ?? null;
    } catch (error) {
      this.logger.error(`Error finding contact by phone: ${error.message}`);
      return null;
    }
  }

  /**
   * Update contact with last message info
   */
  async updateLastMessage(
    contactId: string,
    messagePreview: string,
    messageType: string = 'text',
  ): Promise<void> {
    try {
      await db
        .update(contacts)
        .set({
          lastMessageTime: new Date(),
          lastMessagePreview: messagePreview,
          lastMessageType: messageType,
          updatedAt: new Date(),
        })
        .where(eq(contacts.contactId, contactId));
    } catch (error) {
      this.logger.error(
        `Error updating contact last message: ${error.message}`,
      );
    }
  }
}
