/**
 * Script: Fix isAiGenerated flag for historical AI messages
 *
 * Run with: npx tsx src/database/scripts/fix-ai-generated.ts
 *
 * This script updates existing outbound messages that were generated by the AI
 * but weren't marked with isAiGenerated = true.
 */

import 'dotenv/config';
import { sql } from 'drizzle-orm';
import { db } from '../db.connection';

async function fixAiGeneratedFlag() {
  console.log('🔧 Fixing isAiGenerated flag for historical AI messages...\n');

  try {
    // Update ALL outbound messages to be AI-generated
    // In this system, all historical outbound messages were AI-generated
    const result: any = await db.execute(sql`
      UPDATE messages
      SET is_ai_generated = true, updated_at = NOW()
      WHERE direction = 'outbound'
        AND (is_ai_generated IS NULL OR is_ai_generated = false)
      RETURNING message_id
    `);

    const updatedCount = result?.rows?.length ?? result?.rowCount ?? 0;
    console.log(
      `✅ Updated ${updatedCount} messages with isAiGenerated = true\n`,
    );

    // Verify the fix
    const afterCount: any = await db.execute(sql`
      SELECT COUNT(*)::int as count
      FROM messages
      WHERE direction = 'outbound'
        AND is_ai_generated = true
    `);

    const totalCount = afterCount?.rows?.[0]?.count ?? 0;
    console.log(`📊 Total AI-generated messages now: ${totalCount}`);

    console.log('\n✅ Done! Restart the server for changes to take effect.');
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }

  process.exit(0);
}

fixAiGeneratedFlag();
