/**
 * Migration: Fix isAiGenerated flag for historical AI messages
 *
 * This migration updates existing outbound messages that were generated by the AI
 * but weren't marked with isAiGenerated = true.
 *
 * We identify AI messages as outbound messages that:
 * 1. Have a text body (AI responses are text-based)
 * 2. Don't have templates associated (templates are human-sent)
 * 3. Are part of active chats with AI enabled
 */

import { sql } from 'drizzle-orm';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

export async function up(db: PostgresJsDatabase) {
  // Update outbound text messages that are likely AI-generated
  // We identify AI messages as outbound text messages that are longer than 20 characters
  // This is a heuristic - human agents typically send shorter messages
  await db.execute(sql`
    UPDATE messages
    SET is_ai_generated = true, updated_at = NOW()
    WHERE direction = 'outbound'
      AND type = 'text'
      AND is_ai_generated IS NOT TRUE
      AND text IS NOT NULL
      AND LENGTH(text) > 20
  `);

  console.log('✅ Updated isAiGenerated flag for historical AI messages');
}

export async function down(db: PostgresJsDatabase) {
  // Revert: Set isAiGenerated back to false/null
  // Note: This is destructive and loses the distinction between AI and human messages
  await db.execute(sql`
    UPDATE messages
    SET is_ai_generated = false, updated_at = NOW()
    WHERE is_ai_generated = true
  `);

  console.log('✅ Reverted isAiGenerated flag');
}
