-- Migration: 094_add_ai_context_and_goal_override
-- Description: Add goal_type to chat_ai_overrides and create chat_ai_context table
-- for efficient conversation context storage

-- ============================================================================
-- Part 1: Add goal_type to chat_ai_overrides
-- This allows each chat to have its own AI goal when resumed
-- ============================================================================

ALTER TABLE chat_ai_overrides
ADD COLUMN IF NOT EXISTS goal_type VARCHAR(50) DEFAULT NULL;

ALTER TABLE chat_ai_overrides
ADD COLUMN IF NOT EXISTS goal_description TEXT DEFAULT NULL;

COMMENT ON COLUMN chat_ai_overrides.goal_type IS 'Per-chat AI goal override (answer_faq, qualify_lead, book_appointment, handle_support, custom)';
COMMENT ON COLUMN chat_ai_overrides.goal_description IS 'Custom description for the goal when goal_type is custom';

-- ============================================================================
-- Part 2: Create chat_ai_context table
-- Stores conversation summaries for efficient context loading when AI resumes
-- ============================================================================

CREATE TABLE IF NOT EXISTS chat_ai_context (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chat_id VARCHAR(255) NOT NULL UNIQUE,
    
    -- Context summary (generated by AI when triggered)
    context_summary TEXT,
    
    -- Key conversation facts extracted by AI
    key_facts JSONB DEFAULT '[]'::jsonb,
    
    -- Customer sentiment/mood from last interaction
    customer_sentiment VARCHAR(50),
    
    -- Open questions or pending issues
    pending_items JSONB DEFAULT '[]'::jsonb,
    
    -- Last topic discussed
    last_topic VARCHAR(255),
    
    -- Message tracking for incremental updates
    last_summarized_message_id VARCHAR(255),
    message_count_at_summary INTEGER DEFAULT 0,
    
    -- Timestamps
    last_summarized_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Foreign key (soft - chat_id is varchar)
    CONSTRAINT fk_chat_ai_context_chat
        FOREIGN KEY (chat_id) REFERENCES chats(chat_id) ON DELETE CASCADE
);

-- Indexes for efficient lookups
CREATE INDEX IF NOT EXISTS idx_chat_ai_context_chat_id ON chat_ai_context(chat_id);
CREATE INDEX IF NOT EXISTS idx_chat_ai_context_last_summarized ON chat_ai_context(last_summarized_at);

-- Comments
COMMENT ON TABLE chat_ai_context IS 'Stores AI-generated conversation summaries for efficient context loading';
COMMENT ON COLUMN chat_ai_context.context_summary IS 'AI-generated summary of conversation history';
COMMENT ON COLUMN chat_ai_context.key_facts IS 'Important facts about customer/conversation extracted by AI';
COMMENT ON COLUMN chat_ai_context.customer_sentiment IS 'Customer mood: positive, neutral, negative, frustrated, etc.';
COMMENT ON COLUMN chat_ai_context.pending_items IS 'Open questions or unresolved issues';
COMMENT ON COLUMN chat_ai_context.last_topic IS 'Main topic from last interaction';
COMMENT ON COLUMN chat_ai_context.last_summarized_message_id IS 'Message ID where summarization stopped';
COMMENT ON COLUMN chat_ai_context.message_count_at_summary IS 'Total messages when summary was created';
